import streamlit as st

col1, col2, col3, col4 = st.columns([0.8,3,0.8,1])
col1.image('https://static.vecteezy.com/system/resources/previews/000/643/339/original/office-building-icon-vector.jpg')
col2.header(':blue[EduTech]')
col2.markdown (' Digital Titans Team-027')
col3.image('https://adityabirlaschools.co.in/abps-khor/wp-content/uploads/sites/5/2022/08/logo.png')
col4.markdown ('The Aditya Birla Public School Kovaya')
st.image('https://indiaschoolaccess.com/wp-content/uploads/2019/10/Lit-Rate-1.png')
st.markdown ('This is literacy growth chart of India')
coc1, coc2, coc3 = st.columns([2,3,1])
coc2.markdown (' # :green[Education Developers]')
coc23, coc24 = st.columns([6,4])
coc23.markdown (' ## :orange[Digital India]')
coc23.markdown ('Digital India is a campaign launched by the Government of India in order to ensure that the Governments services are made available to citizens electronically by improved online infrastructure and by increasing Internet connectivity or making the country digitally empowered in the field of technology.')
coc24.image ('https://th.bing.com/th/id/R.5c29a8dc54b58f26a5b0c27af0575871?rik=CXELgkKOwDZ%2b0w&riu=http%3a%2f%2fcdn.ndtv.com%2ftech%2fimages%2fgadgets%2fthumb%2fdigital_india_logo_small.jpg&ehk=1lnoGl%2bjunZWAigjPJDSKb4v4LmIEFl%2bjwKjK4WExbA%3d&risl=&pid=ImgRaw&r=0')
coc13, coc14 = st.columns([6,4])
coc23.markdown (' ## :blue[Hybrid Learning]')
coc23.markdown ('Hybrid learning is an educational model where some students attend class in-person, while others join the class virtually from home. Educators teach remote and in-person students at the same time using tools like video conferencing hardware and software.')
coc24.image ('https://blog.mimio.com/hs-fs/hubfs/Future%20of%20hybrid%20learning%20banner.png?width=1200&name=Future%20of%20hybrid%20learning%20banner.png')
coc3, coc4 = st.columns([6,4])
coc3.markdown (' ## :green[Artificial Intelligence]')
coc3.markdown ('Artificial intelligence is intelligence—perceiving, synthesizing, and inferring information—demonstrated by machines, as opposed to intelligence displayed by non-human animals or by humans.')
coc4.image ('https://qph.fs.quoracdn.net/main-qimg-b11429713f76816ddfa65eb2671e9ca9')
coc33, coc40 = st.columns([6,4])
coc33.markdown (' ## :red[National Education Policy]')
coc33.markdown ('The National Education Policy of India 2020 (NEP 2020), which was started by the Union Cabinet of India on 29 July 2020, outlines the vision of new education system of India.[1] The new policy replaces the previous National Policy on Education, 1986.[a] The policy is a comprehensive framework for elementary education to higher education as well as vocational training in both rural and urban India. The policy aims to transform Indias education system by 2030')
coc40.image ('https://advocatetanwar.com/wp-content/uploads/2020/09/image0-1.jpeg')
st.markdown (' # :red[Problems] Related To :blue[Education System]')
st.markdown (' ## :red[Problem 1 : Tutor Student Ratio]')
st.markdown ("The major problem of Indian Education System is :- Student and Teacher ratio – India’s student and teacher ratio is lowest among compared to other countries. India trails behind several countries including Brazil and China in terms of student-teacher ratio in higher education segment, a government report has revealed. The 24:1 ratio of India is lower than 19:1 in Brazil and China. Among the eight countries compared, India's student-ratio has turned out to be the lowest - against Swedens 12:1, Britain's 16:1, Russia's 10:1 and Canada's 9:1.")
st.image ('https://1.bp.blogspot.com/-ABTCwUXgoxY/XZiqZPL7ppI/AAAAAAAAQRU/cek_o9SoQHMWCNo39dXPALtiEi3C_ntRQCLcBGAsYHQ/s1600/oversized.jpg')
st.markdown (' ## :green[Solution 1 : Tutor Student Ratio]')
st.markdown ('Section in every school and class must be increased so teacher can focus on each and every child. In overcrowded class the teacher isn’t able to give a special attention to each particular student of the class, this is also one of the major problem which creates the word backbencher or indiscipline in class which is due to lack of attention of tutor')
st.image ('https://teachmiddleeastmag.com/wp-content/uploads/2016/03/S.-Mulligan-Blog-11.jpg')
st.markdown (' ## :red[Problem 2 : Innovation required]')
st.markdown ('In India the students are pressured to mainly score the grades instead of  developing the ability to think, High order thinking, Problem Solving Mindset and Critical solutions which is the main part for their career as being a civil servant a lawyer engineer, a doctor etc. ')
st.image ('https://img.graphicsurf.com/2018/10/deszone-innovation-for-business-illustration-vector-free1.jpg')
st.markdown (' ## :green[Solution 2 : Innovation required]')
st.markdown ("Introducing more technology in the classroom to create a blended  classroom where students experience technology as they would in the real world. Providing greater ways to facilitate clearer and better communication between school districts’ parents with powerful video tools.")
st.markdown ('There are many more problems but in this project we have just included this only.')
st.markdown (' ## :orange[Thank You] :thumbsup:')
st.markdown ('Copiright @ 2023, Digital Titans')